name: CI

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  ci:
    name: ci
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          ref: ${{ github.event.pull_request.head.ref }}
          repository: ${{github.event.pull_request.head.repo.full_name}}
      - uses: actions/cache@v4
        with:
          path: |
            ~/.cargo/registry
            ~/.cargo/git
            target
          key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: nightly-2022-10-22
          components: rustfmt, clippy
      - uses: actions-rs/cargo@v1
        name: format check
        with:
          command: fmt
          args: --all -- --check
      - uses: actions-rs/cargo@v1
        name: clippy check
        with:
          command: clippy
          args: -- -D warnings
      - uses: actions-rs/cargo@v1
        name: unit-test
        with:
          command: test
          args: --release --features=std --manifest-path light-client/Cargo.toml
      - uses: actions-rs/cargo@v1
        name: unit-test-dev-test-min
        with:
          command: test
          args: --release --features=dev --manifest-path light-client/Cargo.toml --lib test::dev_test_min
        env:
          MINIMUM_TIMESTAMP_SUPPORTED: 1731495592
          MINIMUM_HEIGHT_SUPPORTED: 100
      - uses: actions-rs/cargo@v1
        name: unit-test-dev-test-pascal
        with:
          command: test
          args: --release --features=dev --manifest-path light-client/Cargo.toml --lib test::dev_test_after_pascal
        env:
          MINIMUM_TIMESTAMP_SUPPORTED: 1
          MINIMUM_HEIGHT_SUPPORTED: 1
          PASCAL_TIMESTAMP: 1
      - uses: actions-rs/cargo@v1
        name: unit-test-dev-test-pascal
        with:
          command: test
          args: --release --features=dev --manifest-path light-client/Cargo.toml --lib test::dev_test_before_pascal
        env:
          MINIMUM_TIMESTAMP_SUPPORTED: 1
          MINIMUM_HEIGHT_SUPPORTED: 1
          PASCAL_TIMESTAMP: 1800000000