name: CI

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  ci:
    name: ci
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions-rust-lang/setup-rust-toolchain@v1
      - uses: Swatinem/rust-cache@v2
      - name: Install components
        run: |
          rustup component add rustfmt clippy
          cargo install cargo-machete --version 0.8.0
      - name: Check format
        run: cargo fmt --all -- --check
      - name: Check clippy
        run: cargo clippy --locked -- -D warnings
      - name: Check deps
        run: cargo machete
      - name: unit-test
        run: cargo test --release --features=std --manifest-path light-client/Cargo.toml
      - name: unit-test-dev-test-min
        run: cargo test --release --features=dev --manifest-path light-client/Cargo.toml --lib test::dev_test_min
        env:
          MINIMUM_TIMESTAMP_SUPPORTED: 110
          MINIMUM_HEIGHT_SUPPORTED: 100
